controller_frequency: 4

DWAPlannerROS:
  max_vel_x: 0.3 #0.5
  min_vel_x: 0.0 #0.01
  max_vel_theta: 1.5 #1.5
  max_vel_trans: 0.7

  min_in_place_vel_theta: 0.1
  max_vel_rot: 0.8
  min_vel_rot: 0.1

  acc_lim_theta: 1.0
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  sim_time: 1.5

  vx_samples: 3.0
  vy_samples: 10.0
  vtheta_samples: 20.0

  occdist_scale: 0.05

  path_distance_bias: 32
  goal_distance_bias: 12
  
  forward_point_distance: 0.15
  stop_time_buffer: 2.0
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  publish_cost_grid_pc: true
  publish_cost_grid: true
  publish_traj_pc: true
  meter_scoring: true
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true


