map_type: costmap

obstacle_range: 4.0 # 2.0
raytrace_range: 8.0 # 3.0

transform_tolerance: 0.15 # 0.0

robot_radius: 0.20 # 0.0
inflation_radius: 2.0 # 0.0
inflation_unknown: false
cost_scaling_factor: 5.0 # 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}
